### PR TITLE
Browser titles

### PR DESCRIPTION
**Pull request by blynch11p**
Update the browser title on each of the pages on the site (Profile, Bookmarks, each Listing, Settings, etc)

click through the site and view the browser's title to test
@irtiza-rizvi : Listing Management is haunted.  That's the only page that won't 'hold' it's title.

### CODE REVIEW

**Comment by irtiza-rizvi** [comment]
@blynch11p it's because the `Management` component implements `shouldComponentUpdate` :frowning_face:.  Every time the redux store is updated, `render` is called on `App` (and all other connected components), unless `shouldComponentUpdate` is false.  This is why `document.title` gets overridden on the listing management page.

As a quick fix, I think getting rid of `shouldComponentUpdate` on listing management should work.

**Comment by flesher1** [comment]
:( Console/Compile error

**Comment by blynch11p** [comment]
Oops! Fixed.

**Comment by flesher1** [comment]
:+1:  everything looks good

**Comment by irtiza-rizvi** [comment]
changes fixed existing issues :+1:

**Pull request merged**
