### PR TITLE
AMLOS-938-Adds NF Message to New Listing Classification

### PR DESCRIPTION
**Pull request by SeanGuy11**
Adds NF message when selecting NF in the classification of a new lisitng.

### CODE REVIEW

**Comment by adegennaro** [comment]
:-1: the error does not display when I click NF.

**Comment by SeanGuy11** [comment]
I double checked the branch this morning and it still works. Please see the attachment for the screen cap. I will have Andrea verify this tody. 

Screenshot from 2019-03-13 07-26-38

**Comment by adegennaro** [comment]
:+1:

**Comment by cjdubois19** [comment]
:+1:

**Pull request merged**
