### PR TITLE
Create edit require feilds

### PR DESCRIPTION
**Pull request by flesher1**
Adds checking if required fields are filled in for submission.
Adds checking for if there are enough screenshots and contacts.

Checks for title, security marking, and contact type for saving. Gives an alert (open to other options).
Automatically adds current user and their org to owners section.

### CODE REVIEW

**Comment by blynch11p** [comment]
I'll run another test, but, I hit a point where I was asked to provide a screenshot, and when I clicked Add New I got a console error for `this.props.value.largeImage is undefined`

**Comment by blynch11p** [comment]
I can't get past that error.  Once I was able to click that button and it worked, but in general if i go about the process of adding text/icons/etc and click Add New screenshot, i get the gray screen of death.

**Comment by blynch11p** [comment]
Looks good to me :+1:

**Comment by irtiza-rizvi** [comment]
:+1:

**Pull request merged**
