### PR TITLE
Create edit delete draft button

### PR DESCRIPTION
**Pull request by flesher1**
Adds functionality to support deletion of draft listings without
approval by steward

refactor delete button code

### CODE REVIEW

**Comment by blynch11p** [comment]
Using Julia:
Pending Deletion undo tooltip now says 'Delete' instead of 'Undelete' 
Drafts are still being moved to Pending Deletion, but without a prompt for why.
:-1:

**Comment by flesher1** [comment]
@blynch11p These issues should be fixed

**Comment by mleeBoeing** [comment]
:+1:

**Comment by blynch11p** [comment]
:+1:

**Pull request merged**
