### PR TITLE
feat(createEdit): require contact types

### PR DESCRIPTION
**Pull request by flesher1**
Adds requirements for contact types in validation method
removes the requirement of minimum 3 contacts

Closes #AMLOS-810

### CODE REVIEW

**Comment by mleeBoeing** [comment]
Getting the warning `Warning: Listing Not Published` twice when trying to Save a newly created listing. (I did not fill out Graphics or Owners sections)

**Comment by flesher1** [comment]
@mleeBoeing I have created another ticket to address this and remove the warnings from createEdit before the listing has been published.

**Comment by mleeBoeing** [comment]
:+1:

**Comment by blynch11p** [comment]
:+1:

**Pull request merged**
