### PR TITLE
 feat(listing mgmt): table view

### PR DESCRIPTION
**Pull request by irtiza-rizvi**
AMLOS-688

**Description**
Replicate the Listing Management grid view in table form.

**Acceptance Criteria**
- The user can switch between Grid View and Table View on the Listing Management page.
- The user should be able to Edit/View/Delete a listing from table view.
- See AML 2.0 Table View for ideas.

**How to Test**
- Pull this branch
- Go to listing management as different users (bigbrother, bettafish, etc)
- Verify that you can toggle between grid/table view on different sections (my listings, all listings, org listings)
- Verify that table sorts
- Verify that table actions (edit, view, delete, toggle featured, etc) are performed as expected

AMLOS-745

**Description**
As a user, I would like the ability to load items in small chunks, loading more as necessary.

**Acceptance Criteria**
- User can load next and prev from each view in listing management
- Loading next and prev updates the current page the user is viewing
- Only applies to table view

**How to Test**
- Pull this branch
- Go to listing management as different users (bigbrother, bettafish, etc)
- Toggle view to open up the table view.  Verify that the table always has 24 rows.
- If there is a next set of listings to be loaded, verify that the _Next_ button is present and that clicking it loads the next page.
- If there is a previous set of listings to be loaded, verify that the _Previous_ button is present and that clicking it loads the previous page.

### CODE REVIEW

**Comment by irtiza-rizvi** [comment]
In addition to the acceptance criteria for the ticket, this PR includes dark theme styling updates for `ReactTable` specific views (settings and listing management), and fixes to the header buttons in `CreateEdit`

**Comment by blynch11p** [comment]
This is good!  The logic involved for when to show which buttons/dropdowns is... crazy.
  
For some future thoughts/another ticket (need UX input):
- maybe the Row # in the table view (1,2,3, etc), and/or a count next to the Prev/Next buttons (1-24, 25-50 - or 25-44 if a lesser number)
- need the status icon for a Listing while in Listing management.  We might be able to get away with keeping the overall ListingTile component, just with that visual indicator. 

:+1:

**Comment by flesher1** [comment]
This is great. it all looks really good put together.
There a few things that might want to be done in a future ticket (these changes should be reviewed by UX):

-  2.0 remembers what you had the view set to (table or tile) on page reload
- 2.0 allows you to search the table
- 2.0 allows you to remove columns you dont want to see and saves it to a cookie.

The only complaint I have is that the seems to be an issue with caching. It looks like if you make a modification to a listing (click the edit button, make the change, and click listing management button from hamburger menu or opening the listing, disabling, then navigating to the listing management page) the change wont be shown until you reload the page. This issues is for both tile and table view but becomes more apparent in table view.

**Comment by irtiza-rizvi** [comment]
@blynch11p @flesher1 I addressed the issue where creating/editing a listing requires a reload of listing management listings.  I agree that the items mentioned should be for a future ticket.

**Comment by flesher1** [comment]
:+1:  looks good

**Pull request merged**
