### PR TITLE
feat(notifications): full notifications page

### PR DESCRIPTION
**Pull request by irtiza-rizvi**
AMLOS-699

**Description**
The user should be able to view all notifications on a separate page after clicking the See More button on their notifications dropdown.

**Acceptance Criteria**
The user can click the see more button from the notifications dropdown to take them to a page to view and interact with all their notifications.

**How to Test**
Pull this branch
Click the notifications icon from the header and click 'See More'
Ensure the notifications are displayed and the user can interact with them like in the popup (ie delete, mark read/unread, etc)

### CODE REVIEW

**Comment by blynch11p** [comment]
Looks good :+1:

**Comment by irtiza-rizvi** [comment]
@blynch11p made some updates, added a mark all read/unread feature

**Comment by blynch11p** [comment]
Nice! :+1:

**Comment by flesher1** [comment]
Reviewed. Code looks good. 

Boxes don't expand when the user types in more than what the box fits on one line. Character limit to appear on the line is currently around 170 character.

**Comment by irtiza-rizvi** [comment]
@flesher1 pushed some updates, check now

**Comment by flesher1** [comment]
:+1: Looks good now.

**Pull request merged**
