### PR TITLE
Bookmark improvements

### PR DESCRIPTION
**Pull request by blynch11p**
Small style changes on the bookmark page

Users can duplicate folders from the action menu.

Biggest change is from a Listing page:
 * Hover over the bookmark icon to see a list of available folders
 * click bookmark icon to add bookmark to root folder
 * click bookmark folder to add bookmark to that folder
 * click again to remove the bookmark from that folder
 * click + New Folder to create a new folder for the bookmark - enter name in text box and click OK
 * view bookmarks in folders - helpful for folder with the same name
 * folders that the user is not an owner of and cannot modify will not show up in the dropdown

### CODE REVIEW

**Comment by flesher1** [comment]
:+1: looks good

**Comment by blynch11p** [comment]
@flesher1 @irtiza-rizvi 
this is finally actually ready for review.

**Comment by flesher1** [comment]
functionally good. :+1: I think duplicate is really good.

**Comment by irtiza-rizvi** [comment]
I think this PR needs a few more commits, but really nice improvements :+1:

**Pull request merged**
