### PR TITLE
fix(createEdit): Fix tag updating in createEdit

### PR DESCRIPTION
**Pull request by flesher1**
Fix issues with entering and saving new tags for existing listings.
Adds searching and saving of existing tags.

Closes #AMLOS-711

Everything will work as expected. The tag search does not use an action. Adding a dispatch to a sub-component of create edit was breaking the parents access to the child's store. If you have run into this, let me know.

Also:
fix(createEdit): improved routing

Adds routing warnings to create edit.
Adds duplication warning
Fixes category select issues on existing listings

Closes #AMLOS-728, #AMLOS-711

### CODE REVIEW

**Comment by irtiza-rizvi** [comment]
Tag drop-down works great, although I'm debating whether or not it would be better with `closeOnSelect={false}`.  In testing this though, I noticed that the category drop-down not only doesn't filter out selected categories (ie if the listing has `Communication` already selected as a category, the drop-down still has that option), but also breaks after selecting one category.

**Comment by blynch11p** [comment]
For consistency, I'm good with the addition of `closeOnSelect={false}` to match the category dropdown functionality.

@irtiza-rizvi , what do you mean breaks?  I don't see to have an issue selecting categories.  They do remove when I initially select them, but when I do to newly edit a page, the entire list IS populated.

**Comment by blynch11p** [comment]
Looks like `closeOnSelect` was added to Categories, not Tags.

Clicking duplicate after editing a current listing does two things:
- pops up two alerts about leave (one pretty, one standard JS)
- does not clear our the changes (which... not a problem, except the alert says it does)

**Comment by flesher1** [comment]
All the above should be fixed now.

**Comment by blynch11p** [comment]
All issues appear to be taken care of.  Tags can be edited and saved.  Routing changes after a listing has been modified, and not saved, will alert the user. 

:+1:

**Comment by irtiza-rizvi** [comment]
previously mentioned issues are resolved :+1:

**Pull request merged**
