### PR TITLE
feat(search): add tags to advanced search

### PR DESCRIPTION
**Pull request by flesher1**
Adds tags to advanced search
Adds share search button for url sharing
Adds url search population

Closes #AMLOS-700

### CODE REVIEW

**Comment by blynch11p** [comment]
Works well :+1:

**Comment by irtiza-rizvi** [comment]
Works well.  Couple improvements:

1. Prevent multiple selection of the same tag (can be done by mapping the `value` on the `Select.Async` component to a state variable instead of a props variable)
2. Prevent search from closing after tag is selected.  This happens intermittently.

**Comment by flesher1** [comment]
@irtiza-rizvi The issues should be resolved.

**Comment by skhtet** [comment]
👍

**Pull request merged**
